/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LibreriaRouteImport } from './routes/libreria'
import { Route as GeneraRouteImport } from './routes/genera'
import { Route as CreaRouteImport } from './routes/crea'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AscoltaRouteImport } from './routes/ascolta'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as AuthenticatedFamigliaRouteImport } from './routes/_authenticated/famiglia'
import { Route as AuthenticatedBambinoNuovoRouteImport } from './routes/_authenticated/bambino.nuovo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LibreriaRoute = LibreriaRouteImport.update({
  id: '/libreria',
  path: '/libreria',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneraRoute = GeneraRouteImport.update({
  id: '/genera',
  path: '/genera',
  getParentRoute: () => rootRouteImport,
} as any)
const CreaRoute = CreaRouteImport.update({
  id: '/crea',
  path: '/crea',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AscoltaRoute = AscoltaRouteImport.update({
  id: '/ascolta',
  path: '/ascolta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFamigliaRoute = AuthenticatedFamigliaRouteImport.update({
  id: '/famiglia',
  path: '/famiglia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBambinoNuovoRoute =
  AuthenticatedBambinoNuovoRouteImport.update({
    id: '/bambino/nuovo',
    path: '/bambino/nuovo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascolta': typeof AscoltaRoute
  '/auth': typeof AuthRoute
  '/crea': typeof CreaRoute
  '/genera': typeof GeneraRoute
  '/libreria': typeof LibreriaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/famiglia': typeof AuthenticatedFamigliaRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/bambino/nuovo': typeof AuthenticatedBambinoNuovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascolta': typeof AscoltaRoute
  '/auth': typeof AuthRoute
  '/crea': typeof CreaRoute
  '/genera': typeof GeneraRoute
  '/libreria': typeof LibreriaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/famiglia': typeof AuthenticatedFamigliaRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/bambino/nuovo': typeof AuthenticatedBambinoNuovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ascolta': typeof AscoltaRoute
  '/auth': typeof AuthRoute
  '/crea': typeof CreaRoute
  '/genera': typeof GeneraRoute
  '/libreria': typeof LibreriaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/famiglia': typeof AuthenticatedFamigliaRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/bambino/nuovo': typeof AuthenticatedBambinoNuovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ascolta'
    | '/auth'
    | '/crea'
    | '/genera'
    | '/libreria'
    | '/sitemap.xml'
    | '/famiglia'
    | '/api/stt'
    | '/api/tts'
    | '/bambino/nuovo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ascolta'
    | '/auth'
    | '/crea'
    | '/genera'
    | '/libreria'
    | '/sitemap.xml'
    | '/famiglia'
    | '/api/stt'
    | '/api/tts'
    | '/bambino/nuovo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ascolta'
    | '/auth'
    | '/crea'
    | '/genera'
    | '/libreria'
    | '/sitemap.xml'
    | '/_authenticated/famiglia'
    | '/api/stt'
    | '/api/tts'
    | '/_authenticated/bambino/nuovo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AscoltaRoute: typeof AscoltaRoute
  AuthRoute: typeof AuthRoute
  CreaRoute: typeof CreaRoute
  GeneraRoute: typeof GeneraRoute
  LibreriaRoute: typeof LibreriaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libreria': {
      id: '/libreria'
      path: '/libreria'
      fullPath: '/libreria'
      preLoaderRoute: typeof LibreriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genera': {
      id: '/genera'
      path: '/genera'
      fullPath: '/genera'
      preLoaderRoute: typeof GeneraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crea': {
      id: '/crea'
      path: '/crea'
      fullPath: '/crea'
      preLoaderRoute: typeof CreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascolta': {
      id: '/ascolta'
      path: '/ascolta'
      fullPath: '/ascolta'
      preLoaderRoute: typeof AscoltaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/famiglia': {
      id: '/_authenticated/famiglia'
      path: '/famiglia'
      fullPath: '/famiglia'
      preLoaderRoute: typeof AuthenticatedFamigliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bambino/nuovo': {
      id: '/_authenticated/bambino/nuovo'
      path: '/bambino/nuovo'
      fullPath: '/bambino/nuovo'
      preLoaderRoute: typeof AuthenticatedBambinoNuovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFamigliaRoute: typeof AuthenticatedFamigliaRoute
  AuthenticatedBambinoNuovoRoute: typeof AuthenticatedBambinoNuovoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFamigliaRoute: AuthenticatedFamigliaRoute,
  AuthenticatedBambinoNuovoRoute: AuthenticatedBambinoNuovoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AscoltaRoute: AscoltaRoute,
  AuthRoute: AuthRoute,
  CreaRoute: CreaRoute,
  GeneraRoute: GeneraRoute,
  LibreriaRoute: LibreriaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
