/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaltDashboardRouteImport } from './routes/walt-dashboard'
import { Route as WaltRouteImport } from './routes/walt'
import { Route as TestAudioRouteImport } from './routes/test-audio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LibreriaRouteImport } from './routes/libreria'
import { Route as GeneraRouteImport } from './routes/genera'
import { Route as CreaRouteImport } from './routes/crea'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AscoltaRouteImport } from './routes/ascolta'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as AuthenticatedPuppetRouteImport } from './routes/_authenticated/puppet'
import { Route as AuthenticatedParlaRouteImport } from './routes/_authenticated/parla'
import { Route as AuthenticatedFamigliaRouteImport } from './routes/_authenticated/famiglia'
import { Route as ApiElevenlabsPreviewRouteImport } from './routes/api/elevenlabs/preview'
import { Route as ApiCronDailyStoryRouteImport } from './routes/api/cron/daily-story'
import { Route as AuthenticatedBambinoNuovoRouteImport } from './routes/_authenticated/bambino.nuovo'
import { Route as AuthenticatedAdminPersonaggiRouteImport } from './routes/_authenticated/admin.personaggi'

const WaltDashboardRoute = WaltDashboardRouteImport.update({
  id: '/walt-dashboard',
  path: '/walt-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WaltRoute = WaltRouteImport.update({
  id: '/walt',
  path: '/walt',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAudioRoute = TestAudioRouteImport.update({
  id: '/test-audio',
  path: '/test-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LibreriaRoute = LibreriaRouteImport.update({
  id: '/libreria',
  path: '/libreria',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneraRoute = GeneraRouteImport.update({
  id: '/genera',
  path: '/genera',
  getParentRoute: () => rootRouteImport,
} as any)
const CreaRoute = CreaRouteImport.update({
  id: '/crea',
  path: '/crea',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AscoltaRoute = AscoltaRouteImport.update({
  id: '/ascolta',
  path: '/ascolta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPuppetRoute = AuthenticatedPuppetRouteImport.update({
  id: '/puppet',
  path: '/puppet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParlaRoute = AuthenticatedParlaRouteImport.update({
  id: '/parla',
  path: '/parla',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamigliaRoute = AuthenticatedFamigliaRouteImport.update({
  id: '/famiglia',
  path: '/famiglia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiElevenlabsPreviewRoute = ApiElevenlabsPreviewRouteImport.update({
  id: '/api/elevenlabs/preview',
  path: '/api/elevenlabs/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDailyStoryRoute = ApiCronDailyStoryRouteImport.update({
  id: '/api/cron/daily-story',
  path: '/api/cron/daily-story',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBambinoNuovoRoute =
  AuthenticatedBambinoNuovoRouteImport.update({
    id: '/bambino/nuovo',
    path: '/bambino/nuovo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPersonaggiRoute =
  AuthenticatedAdminPersonaggiRouteImport.update({
    id: '/admin/personaggi',
    path: '/admin/personaggi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascolta': typeof AscoltaRoute
  '/auth': typeof AuthRoute
  '/crea': typeof CreaRoute
  '/genera': typeof GeneraRoute
  '/libreria': typeof LibreriaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-audio': typeof TestAudioRoute
  '/walt': typeof WaltRoute
  '/walt-dashboard': typeof WaltDashboardRoute
  '/famiglia': typeof AuthenticatedFamigliaRoute
  '/parla': typeof AuthenticatedParlaRoute
  '/puppet': typeof AuthenticatedPuppetRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/admin/personaggi': typeof AuthenticatedAdminPersonaggiRoute
  '/bambino/nuovo': typeof AuthenticatedBambinoNuovoRoute
  '/api/cron/daily-story': typeof ApiCronDailyStoryRoute
  '/api/elevenlabs/preview': typeof ApiElevenlabsPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascolta': typeof AscoltaRoute
  '/auth': typeof AuthRoute
  '/crea': typeof CreaRoute
  '/genera': typeof GeneraRoute
  '/libreria': typeof LibreriaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-audio': typeof TestAudioRoute
  '/walt': typeof WaltRoute
  '/walt-dashboard': typeof WaltDashboardRoute
  '/famiglia': typeof AuthenticatedFamigliaRoute
  '/parla': typeof AuthenticatedParlaRoute
  '/puppet': typeof AuthenticatedPuppetRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/admin/personaggi': typeof AuthenticatedAdminPersonaggiRoute
  '/bambino/nuovo': typeof AuthenticatedBambinoNuovoRoute
  '/api/cron/daily-story': typeof ApiCronDailyStoryRoute
  '/api/elevenlabs/preview': typeof ApiElevenlabsPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ascolta': typeof AscoltaRoute
  '/auth': typeof AuthRoute
  '/crea': typeof CreaRoute
  '/genera': typeof GeneraRoute
  '/libreria': typeof LibreriaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-audio': typeof TestAudioRoute
  '/walt': typeof WaltRoute
  '/walt-dashboard': typeof WaltDashboardRoute
  '/_authenticated/famiglia': typeof AuthenticatedFamigliaRoute
  '/_authenticated/parla': typeof AuthenticatedParlaRoute
  '/_authenticated/puppet': typeof AuthenticatedPuppetRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/admin/personaggi': typeof AuthenticatedAdminPersonaggiRoute
  '/_authenticated/bambino/nuovo': typeof AuthenticatedBambinoNuovoRoute
  '/api/cron/daily-story': typeof ApiCronDailyStoryRoute
  '/api/elevenlabs/preview': typeof ApiElevenlabsPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ascolta'
    | '/auth'
    | '/crea'
    | '/genera'
    | '/libreria'
    | '/sitemap.xml'
    | '/test-audio'
    | '/walt'
    | '/walt-dashboard'
    | '/famiglia'
    | '/parla'
    | '/puppet'
    | '/api/stt'
    | '/api/tts'
    | '/admin/personaggi'
    | '/bambino/nuovo'
    | '/api/cron/daily-story'
    | '/api/elevenlabs/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ascolta'
    | '/auth'
    | '/crea'
    | '/genera'
    | '/libreria'
    | '/sitemap.xml'
    | '/test-audio'
    | '/walt'
    | '/walt-dashboard'
    | '/famiglia'
    | '/parla'
    | '/puppet'
    | '/api/stt'
    | '/api/tts'
    | '/admin/personaggi'
    | '/bambino/nuovo'
    | '/api/cron/daily-story'
    | '/api/elevenlabs/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ascolta'
    | '/auth'
    | '/crea'
    | '/genera'
    | '/libreria'
    | '/sitemap.xml'
    | '/test-audio'
    | '/walt'
    | '/walt-dashboard'
    | '/_authenticated/famiglia'
    | '/_authenticated/parla'
    | '/_authenticated/puppet'
    | '/api/stt'
    | '/api/tts'
    | '/_authenticated/admin/personaggi'
    | '/_authenticated/bambino/nuovo'
    | '/api/cron/daily-story'
    | '/api/elevenlabs/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AscoltaRoute: typeof AscoltaRoute
  AuthRoute: typeof AuthRoute
  CreaRoute: typeof CreaRoute
  GeneraRoute: typeof GeneraRoute
  LibreriaRoute: typeof LibreriaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestAudioRoute: typeof TestAudioRoute
  WaltRoute: typeof WaltRoute
  WaltDashboardRoute: typeof WaltDashboardRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiCronDailyStoryRoute: typeof ApiCronDailyStoryRoute
  ApiElevenlabsPreviewRoute: typeof ApiElevenlabsPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/walt-dashboard': {
      id: '/walt-dashboard'
      path: '/walt-dashboard'
      fullPath: '/walt-dashboard'
      preLoaderRoute: typeof WaltDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walt': {
      id: '/walt'
      path: '/walt'
      fullPath: '/walt'
      preLoaderRoute: typeof WaltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-audio': {
      id: '/test-audio'
      path: '/test-audio'
      fullPath: '/test-audio'
      preLoaderRoute: typeof TestAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libreria': {
      id: '/libreria'
      path: '/libreria'
      fullPath: '/libreria'
      preLoaderRoute: typeof LibreriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genera': {
      id: '/genera'
      path: '/genera'
      fullPath: '/genera'
      preLoaderRoute: typeof GeneraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crea': {
      id: '/crea'
      path: '/crea'
      fullPath: '/crea'
      preLoaderRoute: typeof CreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascolta': {
      id: '/ascolta'
      path: '/ascolta'
      fullPath: '/ascolta'
      preLoaderRoute: typeof AscoltaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/puppet': {
      id: '/_authenticated/puppet'
      path: '/puppet'
      fullPath: '/puppet'
      preLoaderRoute: typeof AuthenticatedPuppetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parla': {
      id: '/_authenticated/parla'
      path: '/parla'
      fullPath: '/parla'
      preLoaderRoute: typeof AuthenticatedParlaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/famiglia': {
      id: '/_authenticated/famiglia'
      path: '/famiglia'
      fullPath: '/famiglia'
      preLoaderRoute: typeof AuthenticatedFamigliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/elevenlabs/preview': {
      id: '/api/elevenlabs/preview'
      path: '/api/elevenlabs/preview'
      fullPath: '/api/elevenlabs/preview'
      preLoaderRoute: typeof ApiElevenlabsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily-story': {
      id: '/api/cron/daily-story'
      path: '/api/cron/daily-story'
      fullPath: '/api/cron/daily-story'
      preLoaderRoute: typeof ApiCronDailyStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bambino/nuovo': {
      id: '/_authenticated/bambino/nuovo'
      path: '/bambino/nuovo'
      fullPath: '/bambino/nuovo'
      preLoaderRoute: typeof AuthenticatedBambinoNuovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/personaggi': {
      id: '/_authenticated/admin/personaggi'
      path: '/admin/personaggi'
      fullPath: '/admin/personaggi'
      preLoaderRoute: typeof AuthenticatedAdminPersonaggiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFamigliaRoute: typeof AuthenticatedFamigliaRoute
  AuthenticatedParlaRoute: typeof AuthenticatedParlaRoute
  AuthenticatedPuppetRoute: typeof AuthenticatedPuppetRoute
  AuthenticatedAdminPersonaggiRoute: typeof AuthenticatedAdminPersonaggiRoute
  AuthenticatedBambinoNuovoRoute: typeof AuthenticatedBambinoNuovoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFamigliaRoute: AuthenticatedFamigliaRoute,
  AuthenticatedParlaRoute: AuthenticatedParlaRoute,
  AuthenticatedPuppetRoute: AuthenticatedPuppetRoute,
  AuthenticatedAdminPersonaggiRoute: AuthenticatedAdminPersonaggiRoute,
  AuthenticatedBambinoNuovoRoute: AuthenticatedBambinoNuovoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AscoltaRoute: AscoltaRoute,
  AuthRoute: AuthRoute,
  CreaRoute: CreaRoute,
  GeneraRoute: GeneraRoute,
  LibreriaRoute: LibreriaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestAudioRoute: TestAudioRoute,
  WaltRoute: WaltRoute,
  WaltDashboardRoute: WaltDashboardRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiCronDailyStoryRoute: ApiCronDailyStoryRoute,
  ApiElevenlabsPreviewRoute: ApiElevenlabsPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
